const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
  EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
  SIGN_IN_SUCESS: 'GOOGLE_SIGN_IN_SUCESS',
  SIGN_IN_FAILURE: 'GOOGLE_SIGN_IN_FAILURE',
};

export default UserActionTypes;
